# Generated by Django 5.1 on 2024-08-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='Repeat_Password',
            new_name='Password2',
        ),
        migrations.RenameField(
            model_name='registerform',
            old_name='password',
            new_name='password1',
        ),
    ]
