# Generated by Django 5.1 on 2024-08-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_repeat_password_registerform_password2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='name',
            new_name='username',
        ),
    ]
